remote_theme: pmarsceill/just-the-docs
markdown: kramdown
title: XB15 Docs
description: XB15 custom cosplay solutions
footer_content: "MicroProto is part of the XB15 family<br><strong>Github Repo: </strong><a href='https://github.com/XB15/MicroProto'>https://github.com/XB15/MicroProto</a><br><strong>Docs Github Repo: </strong><a href='https://github.com/XB15/MicroProto'>https://github.com/XB15/MicroProto</a><br><strong>Discord: </strong><a href='https://discord.gg/hZFV7YaY'>https://discord.gg/hZFV7YaY</a>"
